branches:
  only:
    - master
    - develop
language: python
python:
  - "3.5"
  - "3.5-dev" # 3.5 development branch
  - "3.6"
  - "3.6-dev" # 3.6 development branch
# command to install dependencies
install: pip install -r requirements.txt
# command to run tests
script: coverage run -m unittest discover
after_success: coveralls -d .coverage

